### PR TITLE
Fix visualization navigation

### LINKED ISSUE #81: Allow users to navigate to uploaded datasets.
A user requested the ability to integrate with Andromeda. They want to upload a CSV for a user and then navigate to Andromeda to allow to visualize the CSV.

### PR DESCRIPTION
**Pull request by johnbradley**
Changes visualization pages to support browser button navigation. Users can now more easily change the column settings for a visualized dataset by clicking the back browser button.

Breaks up the large visualization page (index.tsx) into three pages:
- Uploading a CSV
- Configuring the visualization
- Explore the visualization

Fixes #81

### CODE REVIEW

File: andromeda-ui/pages/dataset/[dataset]/visualize/index.tsx [hunk 1]
```diff
@@ -0,0 +1,114 @@
...
+import { CSVFilename } from '@/components/CSVFilename';
+import { makeUrlColumnSettings, configureURLQueryDict, UrlColumnSettings } from '@/util/router-utils'
+
+const DEFAULT_POINT_SCALING = 1.0;
+
+
+export default function Home() {
+  const router = useRouter()
+
+  const [datasetID, setDatasetID] = useState<string>();
```
Comment (egrace479) [inline andromeda-ui/pages/dataset/[dataset]/visualize/index.tsx:21]:
```suggestion
  const [datasetID, setDatasetID] = useState<string>("");
```

**Review by egrace479 — APPROVED** [review]
LGTM. The added functionality is great :)

**Review by thompsonmj — APPROVED** [review]
